#Get posts with pagination
GET http://localhost:3333/products?sortField=additionDate&sortDirection=desc HTTP/1.1
###

#Product creation
POST http://localhost:3333/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzZiNmI5OS1jMmIwLTRiYmMtOWU3Yi05YWFmYzhjMWViZjIiLCJlbWFpbCI6ImFraXJhZHJpdmVyQGJpa2UuY29tIiwibmFtZSI6ImFraXJhIiwiaWF0IjoxNzA3ODM0MjAzLCJleHAiOjE3MDc4MzYwMDN9.OuPg-AZ6FxfeWIjsNPzrU2GVju701uC9JcyVUhGrB3s
Content-Type: application/json

{
  "title": "Sample Guitar",
  "description": "Has he lost his mind? Can he see or is he blind?",
  "photoUrl": "server/static/02/12/image.jpeg",
  "guitarType": "акустика",
  "article": "fender-telecaster-1234",
  "stringsCount": 12,
  "price": 400000
}
###

#Show product by id
GET http://localhost:3333/products/5eba2eb4-5a54-484f-8880-c3e70e30c6f7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzZiNmI5OS1jMmIwLTRiYmMtOWU3Yi05YWFmYzhjMWViZjIiLCJlbWFpbCI6ImFraXJhZHJpdmVyQGJpa2UuY29tIiwibmFtZSI6ImFraXJhIiwiaWF0IjoxNzA3ODM0MjAzLCJleHAiOjE3MDc4MzYwMDN9.OuPg-AZ6FxfeWIjsNPzrU2GVju701uC9JcyVUhGrB3s
###

#Product update
PATCH http://localhost:3333/products/5eba2eb4-5a54-484f-8880-c3e70e30c6f7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzZiNmI5OS1jMmIwLTRiYmMtOWU3Yi05YWFmYzhjMWViZjIiLCJlbWFpbCI6ImFraXJhZHJpdmVyQGJpa2UuY29tIiwibmFtZSI6ImFraXJhIiwiaWF0IjoxNzA3ODM0MjAzLCJleHAiOjE3MDc4MzYwMDN9.OuPg-AZ6FxfeWIjsNPzrU2GVju701uC9JcyVUhGrB3s
Content-Type: application/json

{
  "price": 20000
}
###

#Product remove
DELETE http://localhost:3333/products/5eba2eb4-5a54-484f-8880-c3e70e30c6f7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzZiNmI5OS1jMmIwLTRiYmMtOWU3Yi05YWFmYzhjMWViZjIiLCJlbWFpbCI6ImFraXJhZHJpdmVyQGJpa2UuY29tIiwibmFtZSI6ImFraXJhIiwiaWF0IjoxNzA3ODM0MjAzLCJleHAiOjE3MDc4MzYwMDN9.OuPg-AZ6FxfeWIjsNPzrU2GVju701uC9JcyVUhGrB3s
###