#Get posts with pagination
GET http://localhost:3333/products?guitarTypes[]=укулеле&sortField=additionDate&sortDirection=desc HTTP/1.1
###

#Product creation
POST http://localhost:3333/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWE5ODFlNy0wMTFkLTRmMTMtYjMxZC1hOGJjNmI0NzVmZjQiLCJlbWFpbCI6IjQ1ZG9sbGFyc0Byb2xsaW4uY29tIiwibmFtZSI6IjQ1ZG9sbGFycyIsImlhdCI6MTcwNzc1MjkwNSwiZXhwIjoxNzA3NzU0NzA1fQ.3Gqpju4G7gQlwCfj1JUedVLX1sKmRTUF7I4N8yJ-Znc
Content-Type: application/json

{
  "title": "Sample Guitar",
  "description": "Has he lost his mind? Can he see or is he blind?",
  "photoUrl": "server/static/02/12/image.jpeg",
  "guitarType": "акустика",
  "article": "fender-telecaster-1234",
  "stringsCount": 12,
  "price": 400000
}
###

#Show product by id
GET http://localhost:3333/products/5bfe7b51-32dd-4331-920d-4a8c47a426e3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWE5ODFlNy0wMTFkLTRmMTMtYjMxZC1hOGJjNmI0NzVmZjQiLCJlbWFpbCI6IjQ1ZG9sbGFyc0Byb2xsaW4uY29tIiwibmFtZSI6IjQ1ZG9sbGFycyIsImlhdCI6MTcwNzc1MjkwNSwiZXhwIjoxNzA3NzU0NzA1fQ.3Gqpju4G7gQlwCfj1JUedVLX1sKmRTUF7I4N8yJ-Znc
###

#Product update
PATCH http://localhost:3333/products/aa8543a2-1bbf-483f-8e87-1acc2e51298f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWE5ODFlNy0wMTFkLTRmMTMtYjMxZC1hOGJjNmI0NzVmZjQiLCJlbWFpbCI6IjQ1ZG9sbGFyc0Byb2xsaW4uY29tIiwibmFtZSI6IjQ1ZG9sbGFycyIsImlhdCI6MTcwNzc3MTMwMywiZXhwIjoxNzA3NzczMTAzfQ.WWSVTclRWreOoFAJZbKxYw9G8hOgFDsuYL2ggTEhzjY
Content-Type: application/json

{
  "price": 20000
}
###

#Product remove
DELETE http://localhost:3333/products/5bfe7b51-32dd-4331-920d-4a8c47a426e3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWE5ODFlNy0wMTFkLTRmMTMtYjMxZC1hOGJjNmI0NzVmZjQiLCJlbWFpbCI6IjQ1ZG9sbGFyc0Byb2xsaW4uY29tIiwibmFtZSI6IjQ1ZG9sbGFycyIsImlhdCI6MTcwNzc1MjkwNSwiZXhwIjoxNzA3NzU0NzA1fQ.3Gqpju4G7gQlwCfj1JUedVLX1sKmRTUF7I4N8yJ-Znc
###