#Get posts with pagination
GET http://localhost:3333/products?sortField=additionDate&sortDirection=desc HTTP/1.1
###

#Product creation
POST http://localhost:3333/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMTNmODM5Mi0xYWQxLTQzNTYtYmRhYi0zOTRjMDA5NWI3OGUiLCJlbWFpbCI6InNhbmppQHBpcmF0ZS5jb20iLCJuYW1lIjoiU0FOSkkiLCJpYXQiOjE3MDg0MjM0NzYsImV4cCI6MTcwODQyNTI3Nn0.WNuKh6X0dloOsb-8SaFnN3AcdOHZwvno30o4tcPAzZI
Content-Type: application/json

{
  "title": "Sample Guitar",
  "description": "Has he lost his mind? Can he see or is he blind?",
  "photoUrl": "server/static/02/12/image.jpeg",
  "guitarType": "акустика",
  "article": "fender-telecaster-1234",
  "stringsCount": 12,
  "price": 400000
}
###

#Show product by id
GET http://localhost:3333/products/3ecc98f8-1233-4325-9de2-d00ae5860929 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMTNmODM5Mi0xYWQxLTQzNTYtYmRhYi0zOTRjMDA5NWI3OGUiLCJlbWFpbCI6InNhbmppQHBpcmF0ZS5jb20iLCJuYW1lIjoiU0FOSkkiLCJpYXQiOjE3MDg0MjM0NzYsImV4cCI6MTcwODQyNTI3Nn0.WNuKh6X0dloOsb-8SaFnN3AcdOHZwvno30o4tcPAzZI
###

#Product update
PATCH http://localhost:3333/products/3ecc98f8-1233-4325-9de2-d00ae5860929 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMTNmODM5Mi0xYWQxLTQzNTYtYmRhYi0zOTRjMDA5NWI3OGUiLCJlbWFpbCI6InNhbmppQHBpcmF0ZS5jb20iLCJuYW1lIjoiU0FOSkkiLCJpYXQiOjE3MDg0MjM0NzYsImV4cCI6MTcwODQyNTI3Nn0.WNuKh6X0dloOsb-8SaFnN3AcdOHZwvno30o4tcPAzZI
Content-Type: application/json

{
  "price": 20000
}
###

#Product remove
DELETE http://localhost:3333/products/db1b85f6-2e1c-4a80-8cb1-416d6c88aa05 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTg4NDM0Zi1mMDJkLTQyYWQtYTZiOS04YTIxNjU5MWYwMjEiLCJlbWFpbCI6InNhbmppQHBpcmF0ZS5jb20iLCJuYW1lIjoiU0FOSkkiLCJpYXQiOjE3MDgwMzc3OTksImV4cCI6MTcwODAzOTU5OX0.y3RdG3-nhd9DqO0eqhyVIWmWCiHJq3VZ2T3119cow5M
###