#Register new user
POST http://localhost:3333/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "45dollars",
  "email": "45dollars@rollin.com",
  "password": "blackjet76"
}
###

#Login
POST http://localhost:3333/users/login HTTP/1.1
Content-Type: application/json

{
"email": "45dollars@rollin.com",
"password": "blackjet76"
}
###

# Check auth status
GET http://localhost:3333/users/status HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWE5ODFlNy0wMTFkLTRmMTMtYjMxZC1hOGJjNmI0NzVmZjQiLCJlbWFpbCI6IjQ1ZG9sbGFyc0Byb2xsaW4uY29tIiwibmFtZSI6IjQ1ZG9sbGFycyIsImlhdCI6MTcwNzYwNDI2NCwiZXhwIjoxNzA3NjA2MDY0fQ.-CwB5z79gpP4Kj8uPzT5NGFgfdK7GcQb1VmXLfUxE7Q
###