POST http://localhost:3333/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="123.jpg"

< C:\Users\alien\Documents\123.jpg
###

#Get uploaded file
GET http://localhost:3333/static/2024/02/23f76b83-c0a3-41bf-96c0-1fd2a72f25bd.jpg HTTP/1.1
###